# permissions for end users to view httpchecks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: httpcheck-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: webapp-operator
    app.kubernetes.io/part-of: webapp-operator
    app.kubernetes.io/managed-by: kustomize
  name: httpcheck-viewer-role
rules:
- apiGroups:
  - csye7125-fall2023-group07.operator.souvikdinda.me
  resources:
  - httpchecks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csye7125-fall2023-group07.operator.souvikdinda.me
  resources:
  - httpchecks/status
  verbs:
  - get
