apiVersion: csye7125-fall2023-group07.operator.souvikdinda.me/v1
kind: HttpCheck
metadata:
  labels:
    app.kubernetes.io/name: httpcheck
    app.kubernetes.io/instance: httpcheck-sample
    app.kubernetes.io/part-of: webapp-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: webapp-operator
  name: httpcheck-sample
spec:
  # TODO(user): Add fields here
